web/longwebcam/config/routes.rb
Longwebcam::Application.routes.draw do

  root :to => 'application#index'

  match '/alpha/index', to: 'alpha#index', via: [:get, :post]

  match '/alpha/enter_code', to: 'alpha#enter_code', via: [:get, :post]

  match '/search', to: 'cameras#index', via: [:get]

  resources :cameras do
    collection do
      get 'doSearch'
    end
  end

  resources :images do
    member do
      get 'thumbnail'
    end
    member do
      get 'medium'
    end
  end

  match '/upload', to: 'upload#upload', via: [:post]

  match '/grunt/get_camera_details', to: 'grunt#get_camera_details', via: [:post]

  match '/grunt/ping', to: 'grunt#ping', via: [:post]

  match '/grunt/image_exists', to: 'grunt#image_exists', via: [:post]

end

web/longwebcam/app/models/camera.rb
class Camera < ActiveRecord::Base
    include ActiveModel::ForbiddenAttributesProtection
    include DateRanges
    belongs_to :users
    
    # General associations
    has_many :messages, :dependent => :destroy
    has_many :camera_details, :dependent => :destroy
    has_many :camera_tags, :through => :cameras_tags
    has_many :images
    has_many :events, :through => :cameras_events

    # Associations for basic camera details
    has_one :current_details, -> { order("details_date DESC").limit(1) }, class_name: "CameraDetail"
    has_one :latest_image, -> { where(image_present: 1).order("date DESC").limit(1) }, class_name: "Image"

    # Search scopes
    scope :freetext, -> (text) {where("title LIKE ? OR description LIKE ?", "%#{text}%", "%#{text}%")}

	#####################
    # Constants
	#
	# Codes for camera types
    URL_TYPE = 1
    NET_CONNECTED_TYPE = 2
    STANDALONE_TYPE = 3

    # The date ranges for the camera. Loaded on demand.
    @ranges = nil

    # Determine whether or not this camera has been disabled
    def disabled()
        return disabled == 1 ? true : false
    end

    # Get the image ranges
    def image_ranges
        build_image_ranges
        @ranges.to_json
    end

    # Get the first available image date
    def first_date
        build_image_ranges
        @ranges.first_date
    end

    # Get the latest available image date
    def last_date
        build_image_ranges
        @ranges.last_date
    end

    # Build the image ranges if they don't already exist
    def build_image_ranges
        if @ranges.nil?
            image_dates = Array.new
            images.each do |image|
                image_dates.push image.date
            end

            @ranges = DateRangeSet.new(image_dates)
        end
    end

    # Private methods
    private :build_image_ranges
end

web/longwebcam/app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
	include CameraSearchHelper
	skip_before_action :check_alpha_code

	def index
		render "search"
	end

	def doSearch
		@searchResults = do_camera_search(params)
		render "search_results"
	end

	def show
		@camera = Camera.find(params[:id])
		render "camera"
	end

	def destroy
		head 403
	end

	def update
		head 403
	end

	def create
		head 403
	end

	def new
		head 403
	end

	def edit
		head 403
	end
end

web/longwebcam/app/views/cameras/camera.html.erb
<%= @camera.title %>
<br/>
<img src="<%= medium_image_path(@camera.latest_image) %>"/>
<br/>
<%= @camera.description %>
<br/>
First image: <%= @camera.first_date %>
Latest image: <%= @camera.last_date %>
<div id="timelineContainer"></div>
<script>
    var TIMELINE_OPTIONS = {
        stack: false,
        showCurrentTime: false,
        selectable: false,
        editable: false,
        moment: function(date) {
            return vis.moment(date).utc();
        }
    };
    var ranges =  new vis.DataSet(<%= raw @camera.image_ranges %>);
    var timeline = new vis.Timeline(timelineContainer, ranges, null, TIMELINE_OPTIONS);
</script>

web/longwebcam/app/views/cameras/map.html.erb
<div id="searchFormContainer">
	<%= form_tag("/cameras/doMapSearch", id: 'searchForm', method: "get", remote: true) do |sf| %>
		<%= text_field_tag(:freetext) %>
	<% end %>
</div>
<div id="searchMap">
</div>
<div id="infoPopup">
	<div id="infoTitle">sdfsd</div>
	<img id="infoImage" src="/assets/camera_icon.png"/>
</div>

web/longwebcam/app/views/cameras/search.html.erb
<div id="searchFormContainer">
	<%= form_tag("/cameras/doSearch", id: 'searchForm', method: "get", remote: true) do |sf| %>
		<div id="resultsModeContainer">
			<input id="resultsModeMap" type="radio" name="resultsMode" value="map">
			<label for="resultsModeMap">Map</label>
			<input id="resultsModeList" type="radio" name="resultsMode" value="list" checked="checked">
			<label for="resultsModeList">List</label>
		</div>

		Showing <div id="resultsCount" class="inlineVariable">0 cameras</div>
		<br/>
		Text search:
		<%= text_field_tag(:freetext) %>
	<% end %>
</div>
<div id="searchMap" class="resultsPanel resultsMap"></div>
<div id="searchList" class="resultsPanel resultsList"></div>
<div id="infoPopup">
	<div id="infoTitle">Camera Title</div>
	<img id="infoImage" class="thumbnail" src="/assets/camera_icon.png"/>
</div>